version: '3.2'
services:
    opencart:
        image: ameseguer/opencart
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: "rootpwd"
        networks:
        - dmz2
        deploy:
          mode: replicated
          replicas: 1
          update_config:
            parallelism: 1
            delay: 10s
          restart_policy:
            condition: on-failure
          labels:
            - "traefik.docker.network=dmz"
            - "traefik.port=80"
            - "traefik.enable=true"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.rule=Host:user${PREFIX}exam.akaorigin.com,user${PREFIX}exam.my-juiceshop.com"


    juiceshop:
        image: bkimminich/juice-shop:latest
        networks:
        - dmz2
        deploy:
          mode: replicated
          replicas: 1
          update_config:
            parallelism: 1
            delay: 10s
          restart_policy:
            condition: on-failure
          labels:
            - "traefik.docker.network=dmz"
            - "traefik.port=3000"
            - "traefik.enable=true"
            - "traefik.frontend.entryPoints=http,https,http-filtered,https-filtered"
            -  "traefik.frontend.rule=Host:juiceshop${PREFIX}.akaorigin.com,juiceshop${PREFIX}.my-juiceshop.com"

            
networks:
  dmz2:
    external: true
